services:
  rasa:
    image: cl13ntl3ss/rasa_container
    ports:
      - 5005:5005
    networks:
      - mynetwork
    depends_on:
      - duckling
   
     
  duckling:
    image: rasa/duckling
    ports:
      - 8000:8000
    networks:
      - mynetwork
      
  backend:
    image: cl13ntl3ss/chatbotapp
    ports:
      - 8080:8080
    networks:
      - mynetwork
    depends_on:
      - rasa
      
  frontend:
    image: cl13ntl3ss/chatbotfrontend
    ports:
      - 4200:4200
    networks:
      - mynetwork
    depends_on:
      - backend
   
   
  
networks:
  mynetwork: