# This is a basic workflow to help you get started with Actions
name: CD
on:
  push:
    branches: [main]
  
jobs:
  build-and-push-gcr:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: chatbot-server-376112
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Google Auth
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      -
        name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - 
        name: Build with Maven
        run: mvn clean install --file chatbot/pom.xml
      -
        name: Build Rasa Docker Image
        run: docker build -t rasa_image:latest rasa_container
      -
        name: Build Backend Docker Image
        run: docker build -t backend_image:latest chatbot
      -
        name: Build Frontend Docker Image
        run: docker build -t frontend_image:latest AngularFrontend/chatFE
      -
        name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
      -
        name: Push Docker Image to Container Registry (GCR)
        env:
          GIT_TAG: v.0.1.0
        run: |-
          docker tag frontend_image:latest gcr.io/$PROJECT_ID/frontend_image:latest
          docker tag frontend_image:latest gcr.io/$PROJECT_ID/frontend_image:$GIT_TAG
          docker tag backend_image:latest gcr.io/$PROJECT_ID/backend_image:latest
          docker tag backend_image:latest gcr.io/$PROJECT_ID/backend_image:$GIT_TAG
          docker tag rasa_image:latest gcr.io/$PROJECT_ID/rasa_image:latest
          docker tag rasa_image:latest gcr.io/$PROJECT_ID/rasa_image:$GIT_TAG
